### ISSUE TITLE
It seems this plugin does not work

### ISSUE THREAD

**Issue by gusbemacbe** [Ernir/Kate-bbcode#1]
Hi @Ernir !

I had to create the folders and copied BBCode plugin. I open the BBCode text file with Kate and Kate does not recognise. I set plugins and I did not find the BBCode plugin.

**Comment by gusbemacbe** [comment]
Ah, the README is outdated.

The Kate project developers have changed the plugins path. Now it is `/usr/share/katepart5/syntax`.

**Comment by Ernir** [comment]
Hey, thanks for flagging the issue! I will update the README asap.

**Comment by gusbemacbe** [comment]
Great! Ekkert að þakka, Ernir!

**Comment by Ernir** [comment]
I've updated the README. While doing so, I found another issue - bbcode brackets are not highlighted, unsure if it's due to the current default Kate style or changes in the XML definitions. Will create a separate issue for that.
